### ISSUE TITLE
Suprapunere de div

### ISSUE THREAD

**Issue by EuMirea21** [epicfloppadev/themarcelpiataguy#4]
Atunci cand incerc sa mut gruparea de div "right" si "left" la inceput, se suprapune cu chadchecker si subsitefoartecool
![marcelpiata](https://github.com/epicfloppadev/themarcelpiataguy/assets/123495508/efbc42aa-f1df-4f12-b5b5-ba9f275688b6)

**Comment by PeterPancake695** [comment]
Eu-s pe firefox si imi merge bine lol
Imi instalez acum un browser pe baza de chrome si vad

**Comment by PeterPancake695** [comment]
Merge si de pe chrome

**Comment by PeterPancake695** [comment]
Doar trebuia sa adaugi un <br>

**Comment by PeterPancake695** [comment]
Doar trebuia sa adaugi un br tag

**Comment by EuMirea21** [comment]
sef ai stricat site pls sterge ce ai pus

**Comment by TheMarcelpiataguy** [comment]
fixed
