### ISSUE TITLE
De găsit un alt host pentru website!

### ISSUE THREAD

**Issue by EuMirea21** [epicfloppadev/themarcelpiataguy#5]
Eu astăzi nu mai lucrez nimic la website așa că ați putea vă rog să căutați site-uri de hosting gratuite și să le dați paste aici, vă rog?

**Comment by PeterPancake695** [comment]
Github pages???
Idk lol

**Comment by EuMirea21** [comment]
Nu ma zic alt host adica nu tiiny.site, sa schimbam domain

**Comment by TheMarcelpiataguy** [comment]
am pus github pages
